# -*- coding: utf-8 -*-
"""HF BootCamp.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yfZnd85L0R3j0VbrZfaVFNVM2K1j1itE
"""

!nvidia-smi

from transformers import pipeline

generator = pipeline("text-generation", model = 'gpt2')
response = generator('What is Hugging Fcae',max_length = 40, num_return_sequences =1)
print(response[0]['generated_text'])

from transformers import pipeline
ner = pipeline('ner',grouped_entities = True)
entities = ner('Hugging face is based on NYC andpartner with google with $200 dollar price ')

#Named Entity Recognition

from transformers import pipeline
ner = pipeline('ner',grouped_entities = True)
entities = ner('Hugging face is based on NYC andpartner with google with $200 dollar price ')

#Sentiment Analysis

!pip install transformers datasets

from transformers import pipeline

classifier = pipeline('sentiment-analysis')
result = classifier('I love Hugging Face library very such , it is so nice')
print(result)

from transformers import pipeline

classifier = pipeline('sentiment-analysis')
result = classifier('The food is not tasty')
print(result)

!pip install gradio

import gradio as gr
from transformers import pipeline

classifier = pipeline('sentiment-analysis')
def analyze_sentiment(text):
  return classifier(text)[0]['label']

gr.Interface(fn = analyze_sentiment, inputs ='text', outputs = 'text').launch()

#4 Text to Image model using diffusion pipeline
from diffusers import StableDiffusionPipeline
import torch

model_id = "sd-legacy/stable-diffusion-v1-5"
pipe = StableDiffusionPipeline.from_pretrained(model_id, torch_dtype=torch.float16)
pipe = pipe.to("cuda")

prompt = "beautiful girl walking in street light with a dog"
image = pipe(prompt).images[0]

image.save("beauttiful girl.png")

import gradio as gr
from diffusers import StableDiffusionPipeline
import torch

model_id = "sd-legacy/stable-diffusion-v1-5"
pipe = StableDiffusionPipeline.from_pretrained(model_id, torch_dtype=torch.float16)
pipe = pipe.to("cuda")


def generated_image(prompt):
  image =pipe(prompt).images[0]
  return image
  #image.save(f"outputs/{prompt}.png")

#ui
gr.Interface(
             fn=generated_image,
             inputs = gr.Textbox(label ="Enter your prompt",
             placeholder="e.g. a beautiful girl with blue eyes walking on the road"),
             outputs = gr.Image(type = "pil", label = "Generated Image"),
              title = 'my name is Shravani',
              description = "Enter your prompts and see your generated image").launch()
#prompts
#1. Massive ,mechanical shark-like creature looms over a tumultuous sea battle . Dark blue , metallic shark , with glowing blue the accents , dominates the foreground.
#2. A surreal dreamscape with floating islands and melting clocks in a pastel sky
#3. Cherry blossom trees in full bloom beside a peaceful river in Kyoto
#4. A dragon soaring above a medieval castle during a thunderstorm
#5. A fox with galaxy-patterned fur under a starry night sky